#!/usr/bin/env python

import sys
import argparse
import urllib.request
import json

def executeAction(area, args, data, id=None):
  if id:
    url = "{}{}:{}/{}/{}/{}".format(args.uri, args.host, args.port, area, args.action, id)
  else:
    url = "{}{}:{}/{}/{}".format(args.uri, args.host, args.port, area, args.action)

  jsonData = json.dumps(data)
  postData = jsonData.encode('utf-8')

  headers = {}
  headers['Content-Type'] = 'application/json'

  req = urllib.request.Request(url, postData, headers)
  
  try:
    res = urllib.request.urlopen(req)
    print(res.read().decode('utf-8'))
  except urllib.error.HTTPError as err:
    print("Error: {}".format(err))
    sys.exit(1)
  except urllib.error.URLError as err:
    print("Error: {}".format(err))
    sys.exit(1)

def executeGET(requestURL, args, data):
  url = "{}{}:{}{}".format(args.uri, args.host, args.port, requestURL)
  
  jsonData = json.dumps(data)
  postData = jsonData.encode('utf-8')

  headers = {}
  headers['Content-Type'] = 'application/json'
  
  req = urllib.request.Request(url, postData, headers)

  try:
    res = urllib.request.urlopen(req)
    print(res.read().decode('utf-8'))
  except Exception as err:
    print("Error: {}".format(err))
    sys.exit(1)

def registerAction(args):
  data = {
    'type': getTypeCode(args.type),
    'name': args.name,
    'email': args.email,
    'password': args.password,
    'postal': args.postal
  }

  executeAction('users', args, data)

def loginAction(args):
  data = {
    'email': args.email,
    'password': args.password
  }

  executeAction('users', args, data)

def logoutAction(args):
  data = {
    'email': args.email,
    'token': args.token
  }

  executeAction('users', args, data)

def voteAction(args):
  data = {
    'email': args.email,
    'token': args.token
  }

  executeAction('profiles', args, data, args.user)

def sendAction(args):
  data = {
    'email': args.email,
    'token': args.token,
    'contents': args.contents
  }

  executeAction('messages', args, data, args.user)

def messagesAction(args):
  data = {
    'email': args.email,
    'token': args.token
  }

  executeGET('/messages', args, data)

def searchAction(args):
  data = {
    'email': args.email,
    'token': args.token,
    'query': args.query
  }

  executeAction('profiles', args, data)

def getTypeCode(arg):
  if arg == 'student':
    return 0
  elif arg == 'tutor':
    return 1

def parseArguments():
  parser = argparse.ArgumentParser(description='TutorMe backend API helper.')
  subparsers = parser.add_subparsers(metavar='action', help='Choose an API call to make.', dest='action') 
  
  addRegisterCommands(subparsers)
  addLoginCommands(subparsers)
  addLogoutCommands(subparsers)
  addVoteCommands(subparsers)
  addSendCommands(subparsers)
  addMessagesCommands(subparsers)
  addSearchCommands(subparsers)
   
  parser.add_argument('--ssl', action='store_true', help='Turns on SSL support. (Default: off)')
  parser.add_argument('--host', default='127.0.0.1', help='Host of the application. (Default: 127.0.0.1)')
  parser.add_argument('--port', default='3000', help='Port to connect to. (Default: 3000)', type=int)
  
  args = parser.parse_args()
  
  if not args.action:
    parser.print_help()
    sys.exit(1)

  if args.ssl:
    args.uri = "https://"
  else:
    args.uri = "http://"

  return args

def addRegisterCommands(subparsers):
  registerParser = subparsers.add_parser('register', help='Register for the TutorMe service.')
  registerParser.add_argument('type', choices=['student', 'tutor'], help='Type of the new user.')
  registerParser.add_argument('name', action='store', help='Name of the new user.')
  registerParser.add_argument('email', action='store', help='Email of the new user.')
  registerParser.add_argument('password', action='store', help='Password of the new user.')
  registerParser.add_argument('postal', action='store', help='Postal code of the new user.')

def addLoginCommands(subparsers):
  loginParser = subparsers.add_parser('login', help='Login to the TutorMe service.')
  loginParser.add_argument('email', action='store', help='Email of the user.')
  loginParser.add_argument('password', action='store', help='Password of the user.')

def addLogoutCommands(subparsers):
  logoutParser = subparsers.add_parser('logout', help='Logout of the TutorMe service.')
  logoutParser.add_argument('email', action='store', help='Email of the logged in user.')
  logoutParser.add_argument('token', action='store', help='Token of the logged in user.')

def addVoteCommands(subparsers):
  voteParser = subparsers.add_parser('vote', help='Vote for a user\'s TutorMe profile.')
  voteParser.add_argument('email', action='store', help='Email of the logged in user.')
  voteParser.add_argument('token', action='store', help='Token of the logged in user.')
  voteParser.add_argument('user', action='store', help='Email of the user for which to cast a vote.')

def addSendCommands(subparsers):
  sendParser = subparsers.add_parser('send', help='Send another user a message.')
  sendParser.add_argument('email', action='store', help='Email of the logged in user.')
  sendParser.add_argument('token', action='store', help='Token of the logged in user.')
  sendParser.add_argument('user', action='store', help='Email of the user to send a message.')
  sendParser.add_argument('contents', action='store', help='Message to send.')

def addMessagesCommands(subparsers):
  messagesParser = subparsers.add_parser('messages', help='Retrieve currently pending messages.')
  messagesParser.add_argument('email', action='store', help='Email of the logged in user.')
  messagesParser.add_argument('token', action='store', help='Token of the logged in user.')

def addSearchCommands(subparsers):
  searchParser = subparsers.add_parser('search', help='Search for tutors.')
  searchParser.add_argument('email', action='store', help='Email of the logged in user.')
  searchParser.add_argument('token', action='store', help='Token of the logged in user.')
  searchParser.add_argument('query', action='store', help='Search query to be performed.')

actionMapper = {
  'register': registerAction,
  'login': loginAction,
  'logout': logoutAction,
  'vote': voteAction,
  'send': sendAction,
  'messages': messagesAction,
  'search': searchAction
}

def main():
  args = parseArguments()
  actionMapper[args.action](args)
  sys.exit(0)

if __name__ == '__main__':
  main()

